### ISSUE TITLE
Licence file not aplicable for multiple logins

### ISSUE THREAD

**Issue by pizzasok** [StationQ/Liquid#19]
Hi

This a subtle issue about the licence file.
I have a desktop machine at my institution, but for running tests I prefer logging to another machine which has more cores. When I log to another machine my home folder gets auto mounted. So when I try to run liquid it checks the license file and finds out that it was accepted from a different machine.
So it asks again to accept and then I need to reopen Liquid. But then if I return my desktop I need to accept again and this goes on...

Is there any workaround for this? Probably a multi entry license file? (The machines run linux here.)

Thanks

**Comment by dbwz8** [comment]
The Academic Release is not really designed for multi-machine use. However, all we really care is that the user (you) accepts the license. If you look in your home directory at the _.liquidrc_ file, you'll see that it's plain text. Just keep two copies (one with the name of the machine you use locally and one with the name of the remote machine). Then just swap them before you run. This isn't a security item, just an identification one so that we know you agreed to the license.

**Comment by pizzasok** [comment]
Thank you for the support, I could sort it out this way.
