### ISSUE TITLE
Spin function

### ISSUE THREAD

**Issue by Baitenov** [StationQ/Liquid#32]
Hello, I am working on quantum ising model in Liquid and I found out that function that is used in ising model is stochastic. Is there a deterministic version of function that can be used?

**Comment by dbwz8** [comment]
Email recieved on this issue:

> My name is Adil Baitenov, and I am student from Nazarbayev University, Kazakhstan. Currently I am working with Pr. Patrick Navez on Quantum Ising model using LiQUi|> software created by your group. I have a question about your stochasticity in the example of Ising model provided in manual. do you use Monte Carlo for it? Thank you in advance!

We're having trouble understanding the exact question, so let me take a stab at it. When you run any of the `Spin` examples, the circuit is run many times using a random number generator to decide on measurement outcomes. Everything else (of course) is deterministic. If you make a call to `Ket.RandSeed` you can force the random number generator to start from the same seed for every run.  This should allow you to reproduce the same behavior from run to run. In addition, you could extract the generated circuit `Spin.LastRawCirc` and then initialize the qubits in the `Ket` vector, set the `RandSeed` and then `Run` the circuit. This should give you the same result every time..

Is this what you 're looking for?

**Comment by Baitenov** [comment]
Looks like it is exactly what I need. Thank you!

**Comment by Baitenov** [comment]
Could you please explain what exactly do you run random number generator for? I mean if the circuit itself is deterministic (known initial states and same gates acting on it), what exactly do you mean by running many times to decide outcome? Do you take average or what?

**Comment by alan-geller** [comment]
@Baitenov -- when you perform a measurement, the result is (typically) non-deterministic. While running the same circuit on the same initial state will always result in the same state vector, you have to measure qubits to get the result of your computation. Because the state vector is the same after each run, the probabilities of the different measurement results are the same each time, but the measurement results are random each time. Typically, you perform many runs in order to sample the result space and estimate the probabilities (determined by the state vector) of the possible results.

It is certainly possible to create a quantum circuit that yields deterministic measurement results, which is to say a circuit that generates a final state vector that is totally supported on a single state. Measurements performed on a state vector like this involve no random randomness, but this is not the typical case. For one thing, a circuit that always generates such a state is no more powerful than a classical circuit.

In particular, the circuits generated for the Ising model do not lead to deterministic measurements.

**Comment by Baitenov** [comment]
Thank you for the answer.
I have more questions regarding the Quantum Ising model:
1) Is there way to see the code of spin.Ferro that builds the circuit?
2) Is there a way to reduce the error? I am running the grown gate circuit and I tried to run code several time and to get the average values, but errors were still big.

**Comment by dbwz8** [comment]
1. No, this is internal code. However, generating this circuit is fairly simple. Just `Dump` the circuit out as an example and use that as a template for generating your own. The difficulty is in generating one for every time step (with the different angles and Trotterization) in an efficient manner while you're doing the simulation (highly parallel, multi-threaded code). 

2. The easiest way to eliminate *all* error is to dump out the Ket vector that you want to measure. This will give you all the probabilities exactly. Try `Ket.Dump` with the `doMCC` parameter.
