### ISSUE TITLE
Too many qubits have been allocated

### ISSUE THREAD

**Issue by Calavoow** [StationQ/Liquid#41]
When performing operations on more than 23 qubits I get the following message:
```
Too many qubits have been allocated
```

A simple program to reproduce this is:
```f#
X >< ((Ket(24)).Reset())
```
Why am I getting this message?

I somewhat remember there being a mention of a maximum number of qubits we are allowed to allocate; is this the case here? Would it be possible increase this limit for educational/research purposes? I am implementing algorithm for the gate counts, some purely (non-entangling) classical verification purposes, and for drawing circuit diagrams. As such I do not need to worry too much about the impact on the simulation of this many qubits.

**Comment by dbwz8** [comment]
I'm sorry but one of the restrictions that was put on the software when it was released for public use was the total number of qubits that can be operated on (23 is the current hard limit). However, this is only a restriction when you try to execute gates (this is what you're doing when you map the `X` gate to the `Ket` vector. If you just allocate the qubits you want and then make a circuit (without running it), you will be able to render the circuit and get gate counts. You will NOT be able to optimize the circuit (`GrowGates`) since that is part of the runtime system. An exception to this limit is the stabilizer simulator which is unlimited in the number of qubits you can execute.
