### ISSUE TITLE
Please help me cheat at video games :)

### ISSUE THREAD

**Issue by AceHack** [StationQ/Liquid#53]
Pointer Scanning is a very comming technique used in video game cheating engines (and also hacking) to map dynamically allocated pointers back to a root (static) object.  This process is very limited becaue it's only able to scan a few levels deep like 5 - 7 which in modern games is not deep enough.  Clustered computers are often used to allow for deeper scanning but only allows to all a few more levels deep.  This is a very hard problem for classical computers to solve.

https://www.youtube.com/watch?v=yy2Da6Y8EZA

**Comment by pushebp0x539** [comment]
This is not relevant to this peoject at all and should be closed as it is spam.

**Comment by AceHack** [comment]
I'm very sorry you see this as spam, that was not my intension.  My thought process went as follows.  Is there a computational intensive problem that could likely fit into the quantum framework that if done could grab headlines and attract more people to this community that would not usually be attracted by just scientific and quantum articles.  In putting a problem like this into that quantum framework my hope would be to help build the community around this project to include more computer scientists that have no interest in quantum computers today.  Thanks.

**Comment by dbwz8** [comment]
Much like your other issue... since you're just simulating a quantum computer on a classical one (at the present)... it's hard to attack problems that are intrinsically bad for classical machines. OTOH, one of the uses for simulators like Liquid is to explore classes of algorithms at a small scale that might point the way to large scale solutions on future quantum hardware (e.g., cryptography, chemistry, materials science, machine learning...). If you can characterize the things you want to go after in <30 qubits then you have a  chance to pull off some of the ideas you have in mind. Go for it! <g>
