### ISSUE TITLE
Get FS0193 error when executing fsi --use:Teleport.fsx

### ISSUE THREAD

**Issue by qzwtb** [StationQ/Liquid#54]
It said it cannot load “file:///C:\Liquid\bin\Liquid1.dll”.
It is clearly fsi cannot load Liquid1.dll.
I have no idea what is wrong. 
Can anybody help me?

**Comment by dbwz8** [comment]
_[I'm leaving the suggested steps here... but don't bother for now... there's something wrong with the binaries in the kit due to an incompatible change in Visual Studio. I'll track it down and report back]_

First go into the bin directory and make sure Liquid is working right:
```fsharp
C:\Liquid\bin> .\liquid.exe "__Teleport()"
```
I made this completely verbose so that it would work from both `cmd` and `powershell`

Next, make sure you go into `Add or Remove Programs` and check that you have Visual Studio 2017 installed correctly and that it doesn't need an update (select Modify to be sure). 

This will not run from `fsi.exe` directly (in any case). The correct way to invoke would be something like:
```fsharp
C:\Liquid\bin> .\liquid.exe /s ..\samples\Teleport.fsx "__Teleport()"
```
The problem is, it appears that since we published the software, fsharp (most like the .Net library) has implemented an incompatible change with our system when it tries to perform Reflection on the modules. 

I'll look into this further, but it looks like the binaries that are in the current kit all need to be updated.

**Comment by qzwtb** [comment]
Thank you for your advice. I did use Visual Studio 2017 community version. I can run all the built-in samples successfully by typing something like "liquid __Teleport()" in the cmd. I only have problems when working with fsi.

**Comment by dbwz8** [comment]
_Fixed AFAICT. Please re-open if you still have a problem. Here is the new blurb at the top of the README:_

__2017/11/03 Updated Binaries__
 
The latest version of Visual Studio/.Net/FSharp (2017) is incompatible with the binaries we've previously shipped for LIQ<i>Ui</i>\|&#x232A;. All the compiled examples will work, but new code or compiling from scripts will fail. The current version on the Github site has been updated to fix this. Following the [Getting Started](http://stationq.github.io/Liquid/getting-started/) is the easiest way to re-install everything. If you already have a version of VS2017, then you can skip that piece.
