### ISSUE TITLE
Depolarized and amplitude damping noise in __NoiseAmp()

### ISSUE THREAD

**Issue by ChienAnWang** [StationQ/Liquid#56]
I want to do the simulation of error correction code. So I read the manual and play with NoiseAmp.fsx and QECC.fsx. I don't understand the noise model used in NoiseAmp.fsx. Can anyone help me?
Here are several questions:
1. Before the first relaxation event, the two-qubit state evolves under amplitude damping noise (ADN). But after the first relaxation event, the two-qubit state is fixed at one of {00, 01, 10}. The state stops evolving under the subsequent ADN. The state only changes under another relaxation event or depolarized noise. Is this realistic? If the state is 01, shouldn't it continue evolving under ADN?
2. Before the first depolarized noise (DN), the two-qubit state evolves under ADN. After the first X- or Y-type DN, the two-qubit state is fixed to a certain state a*s1+b*s2, where s1, s2 = {00, 01, 10, 11}. The state stops evolving under the subsequent ADN. The state would restart evolving under ADN only after the subsequent  X- or Y-type DN. What model does this behavior base on?

**Comment by dbwz8** [comment]
It really depends on the circuit you're analyzing as to what you should expect.  Make a change to `NoiseAmp.fsx` where:
```fsharp
    H qs
```
is replaced with:
```fsharp
    H >< qs
```
Now you're doing a Hadamard at on both qubits. You'll now see the effect you're expecting after a hard amplitude damping event. Here is the summary at the end of one such run:
```
0:0000.0/========== Detailed statistics =========
0:0000.0/      Time    Gate Pattern     Dur Wires        Type Detail
0:0000.0/      ----    ------------     --- -----        ---- ------
0:0000.0/     17.00               I     1.0 1            norm depol_Z
0:0000.0/    352.00         AmpDamp     1.0 1            norm <hard>
0:0000.0/    486.00         AmpDamp     1.0 0            norm <hard>
```
Looking around time 352, you see the expected behavior:
```
0:0000.0/ 348,0.44550,0.22196,0.22196,0.11059
0:0000.0/ 349,0.44609,0.22181,0.22181,0.11029
0:0000.0/ 350,0.44668,0.22166,0.22166,0.11000
0:0000.0/ 351,0.44728,0.22151,0.22151,0.10970
0:0000.0/ 352,0.44787,0.22136,0.22136,0.10941
0:0000.0/ 353,0.66967,0.00000,0.33033,0.00000
0:0000.0/ 354,0.67012,0.00000,0.32988,0.00000
0:0000.0/ 355,0.67056,0.00000,0.32944,0.00000
0:0000.0/ 356,0.67100,0.00000,0.32900,0.00000
```
See that after the event, the remaining qubit continues to degrade. Now take a look where the second amplitude damping happens (at 486):
```
0:0000.0/ 483,0.72451,0.00000,0.27549,0.00000
0:0000.0/ 484,0.72491,0.00000,0.27509,0.00000
0:0000.0/ 485,0.72531,0.00000,0.27469,0.00000
0:0000.0/ 486,0.72571,0.00000,0.27429,0.00000
0:0000.0/ 487,1.00000,0.00000,0.00000,0.00000
0:0000.0/ 488,1.00000,0.00000,0.00000,0.00000
0:0000.0/ 489,1.00000,0.00000,0.00000,0.00000
0:0000.0/ 490,1.00000,0.00000,0.00000,0.00000
0:0000.0/ 491,1.00000,0.00000,0.00000,0.00000
0:0000.0/ 492,1.00000,0.00000,0.00000,0.00000
```
I think this is what you were looking for. It all depends on how the qubits were entangled. This is from the noise model used, not necessarily the behavior of the physical system. If you want to be more accurate, I'd use the Kraus operator model demonstrated in [Kraus.fsx](https://github.com/StationQ/Liquid/blob/master/Samples/Kraus.fsx) and documented in the [User's Manual](http://stationq.github.io/Liquid/docs/LIQUiD.pdf) on Advanced Models (specifically Channels and POVMs).
